### ISSUE TITLE
[Todo] basic settings

### ISSUE THREAD

**Issue by ysh4296** [ysh4296/Project_Icarus#1]
# basic settings for frontend

 - [x] add chakra ui for design
 - [x] custom design theme
 - [x] responsive design setting
    - break points with [ sm, md, lg ]
 - [x] test interaction with storybook
 - [ ] e2e test with cypress
