### ISSUE TITLE
[Todo] game dev

### ISSUE THREAD

**Issue by ysh4296** [ysh4296/Project_Icarus#2]
# engine feature

- [X] engine : dynamic canvas size
- [x] engine : canvas zoom handler (with camera position)
- [x] engine : craft mode & play mode
- [x] engine : object Edit
- [x] engine : handle user event type with zustand (engine.registry)
- [x] engine : game board to grid
- [x] engine : game object created on grid system
- [ ] engine : do undo stacks
- [ ] engine : keyboard shortcut

# game object

- [x] game object : bacon
- [x] game object : bread
- [x] game object : escalator
- [x] game object : grill (추가업무: grill의 collision box를 조정하여 cook의 범위 넓히기)
- [x] game object : fan
- [x] game object : grinder
- [x] game object : pressure
- [x] game effect : erasing object event
- [x] game object : spring
- [ ] game object: net
- [ ] game object : filter
- [ ] game object : fluid engine
- [ ] game object : water
- [ ] game object : oil
- [ ] game object : gear (for fluid move)
- [ ] game effect : cooking effect
